import { SITE_NAME } from "@/lib/seo-metadata";

export default function PrivacyPolicyPage() {
  return (
    <article className="mx-auto max-w-2xl space-y-4 pb-8 text-[15px] leading-relaxed text-kal-text sm:text-base">
      <h1 className="text-2xl font-bold tracking-tight text-kal-text sm:text-3xl">
        Privacy Policy
      </h1>
      <p>
        <strong>Last updated:</strong> April 08, 2026
      </p>
      <p>
        Neven Academy Assam operates the {SITE_NAME}
        application available at www.kalnehi.com.
      </p>
      <p>
        <strong>Your use of this app is entirely at your own risk.</strong> We
        make no guarantees regarding the privacy, security, or protection of
        your data.
      </p>
      <p>
        <strong>Information We Collect</strong>
      </p>
      <p>
        We may collect your name, email address, phone number, exam target,
        class/year, study habits, task data, voice recordings, handwritten
        photos, device information, and usage data.
      </p>
      <p>
        <strong>How We Use Your Information</strong>
      </p>
      <p>
        We use this data to provide the service, personalise your experience,
        generate reports, and send notifications. However,{" "}
        <strong>we are not responsible</strong> for how this data is used or
        if it leads to any negative outcome.
      </p>
      <p>
        <strong>AI Features Disclaimer</strong>
      </p>
      <p>
        {SITE_NAME} uses Artificial Intelligence (AI) for features such as
        voice-to-task conversion, planner scanning, and suggestions.{" "}
        <strong>We are not responsible</strong> for any output generated by
        AI. The         AI may give wrong, incomplete, misleading, or hallucinated
        results. We have zero responsibility for any AI-generated content or
        advice.
      </p>
      <p>
        <strong>Data Storage &amp; Protection</strong>
      </p>
      <p>
        Your data is stored using third-party services. We use reasonable
        security measures, but <strong>we do not guarantee</strong> the security
        of your data. We are <strong>not responsible</strong> if your data is
        lost, stolen, leaked, hacked, or misused by any party.
      </p>
      <p>
        <strong>Data Sharing</strong>
      </p>
      <p>
        We may share anonymised or aggregated data with service providers. We
        do not sell your personal data. However,{" "}
        <strong>we are not liable</strong> for any actions taken by third-party
        service providers.
      </p>
      <p>
        <strong>Your Rights</strong>
      </p>
      <p>
        You may request access, correction, or deletion of your data by
        emailing curioversitylearning@gmail.com. We will try to respond, but we
        make no guarantees about response time or action taken.
      </p>
      <p>
        <strong>Children&apos;s Privacy</strong>
      </p>
      <p>
        The app is not intended for children under 13 years of age. We do not
        knowingly collect data from children.
      </p>
      <p>
        <strong>Changes to this Policy</strong>
      </p>
      <p>
        We may update this Privacy Policy at any time. Continued use of the app
        means you accept the updated policy.
      </p>
      <p>
        <strong>Zero Liability</strong>
      </p>
      <p>
        To the maximum extent permitted by law, Neven Academy Assam and its
        owner shall have <strong>zero liability</strong> for any
        privacy-related issues, data breach, loss of data, or any harm resulting
        from your use of {SITE_NAME}.
      </p>
      <p>
        <strong>Contact Us</strong>
      </p>
      <p>
        Neven Academy Assam
        <br />
        1000, Uday Nagar, Bono Durga Mandir, Karim Chowk, K.Chowka, Ward No.4,
        Mangaldoi, Darrang, Assam, 784125
        <br />
        Phone: 9101776379
        <br />
        Email: curioversitylearning@gmail.com
      </p>
    </article>
  );
}
