import type { MetadataRoute } from "next";

import { absoluteSitemapUrl } from "@/lib/site";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/blog",
          "/blog/",
          "/features",
          "/features/",
          "/jee",
          "/jee-main",
          "/jee-advanced",
          "/neet",
          "/neet-pg",
          "/upsc",
          "/upsc-prelims",
          "/upsc-mains",
          "/cat",
          "/gate",
          "/ca-foundation",
          "/ca-intermediate",
          "/ca-final",
          "/clat",
          "/nda",
          "/ssc-cgl",
          "/ssc-chsl",
          "/ibps-po",
          "/sbi-po",
          "/gre",
          "/sat",
          "/cuet",
          "/cbse-class-12",
          "/ipmat",
          "/tools",
          "/tools/",
          "/vs/",
          "/for/",
          "/syllabus/",
          "/pricing",
          "/about",
          "/contact",
          "/guides",
          "/guides/",
          "/changelog",
          "/jee-study-planner",
          "/neet-study-planner",
          "/neet-pg-study-planner",
          "/upsc-study-planner",
          "/cuet-ug-study-planner",
          "/boards-study-planner",
          "/brain-yoga",
          "/what-can-kalnehi-do",
          "/best-study-practices",
          "/privacy",
          "/terms",
          "/search",
        ],
        disallow: [
          "/search?",
          "/api/",
          "/api",
          "/auth/",
          "/auth",
          "/dashboard/",
          "/dashboard",
          "/app/",
          "/app",
          "/settings",
          "/daily-plan",
          "/planner",
          "/syllabus",
          "/prepbrain",
          "/marks-engine",
          "/revision-engine",
          "/study-sessions",
          "/habits",
          "/heatmap",
          "/calendar",
          "/consistency-tracker",
          "/doubts",
          "/motivation",
          "/timer",
          "/meditation",
          "/my-subscription",
          "/my-target",
          "/saved-plans",
          "/onboarding",
          "/profile",
          "/notifications",
          "/feedback",
        ],
      },
    ],
    sitemap: [
      absoluteSitemapUrl("/sitemap.xml"),
      absoluteSitemapUrl("/sitemap-pages.xml"),
      absoluteSitemapUrl("/sitemap-blog.xml"),
      absoluteSitemapUrl("/sitemap-exams.xml"),
    ],
  };
}
