-- Replace all daily motivational phrases with new motivational/winning-mindset quotes.
-- Categories changed from exam-specific to: motivation, mindset, resilience, discipline,
-- focus, consistency, daily_win, growth.

TRUNCATE public.daily_motivational_phrases;

INSERT INTO public.daily_motivational_phrases (phrase, author, category) VALUES
  ('Every champion was once a contender who refused to give up.', null, 'motivation'),
  ('Your hunger today shapes your harvest tomorrow.', null, 'motivation'),
  ('Winners are made in the moments when quitting feels easiest.', null, 'motivation'),
  ('Chase progress, not perfection—progress compounds.', null, 'motivation'),
  ('The fire inside you is stronger than the storm outside.', null, 'motivation'),
  ('You were built for more than average—prove it daily.', null, 'motivation'),
  ('Potential is just discipline waiting to be activated.', null, 'motivation'),
  ('The only ceiling you have is the one you stop pushing against.', null, 'motivation'),
  ('Greatness is not a talent—it is a decision renewed every morning.', null, 'motivation'),
  ('Every effort you make in silence speaks volumes on the day it counts.', null, 'motivation'),
  ('Your best work happens when the applause stops and the real work begins.', null, 'motivation'),
  ('Show up for yourself the way you would for someone you love.', null, 'motivation'),
  ('The world makes room for people who know exactly what they want.', null, 'motivation'),
  ('You do not find motivation—you build it one completed task at a time.', null, 'motivation'),
  ('One bold move today is worth ten timid years of waiting.', null, 'motivation'),
  ('Your future self is watching today''s choices.', null, 'motivation'),
  ('Wanting it is not enough—building it daily is the answer.', null, 'motivation'),
  ('The gap between where you are and where you want to be is bridged by action.', null, 'motivation'),
  ('Momentum is not found—it is made from first steps.', null, 'motivation'),
  ('The person who shows up every day becomes the person everyone looks up to.', null, 'motivation'),
  ('You are not too late—the world still needs what only you can bring.', null, 'motivation'),
  ('Your thoughts are the blueprint—build deliberately.', null, 'mindset'),
  ('A winning mind sees problems as puzzles, not stop signs.', null, 'mindset'),
  ('Adopt the posture of a champion before the crown arrives.', null, 'mindset'),
  ('How you see the obstacle determines whether it stops you or shapes you.', null, 'mindset'),
  ('Train your inner voice to coach you, not critique you.', null, 'mindset'),
  ('Doubt is a question—answer it with action.', null, 'mindset'),
  ('Champions do not wait for confidence; they create it with each repetition.', null, 'mindset'),
  ('Your identity is not what happened to you—it is what you decided to become.', null, 'mindset'),
  ('Pressure is privilege—only the capable get tested at this level.', null, 'mindset'),
  ('Replace ''I can''t'' with ''I haven''t yet'' and watch your world expand.', null, 'mindset'),
  ('The mind that wins is the one that refuses to argue with its own possibilities.', null, 'mindset'),
  ('Success is 90% what you tell yourself between attempts.', null, 'mindset'),
  ('The scoreboard is just your mindset made visible.', null, 'mindset'),
  ('Think like a builder, not a spectator.', null, 'mindset'),
  ('A calm mind is a sharp weapon—protect it.', null, 'mindset'),
  ('What you repeatedly imagine, you eventually become.', null, 'mindset'),
  ('Belief is not a feeling—it is a practice.', null, 'mindset'),
  ('Every setback is a setup; every failure is a syllabus.', null, 'mindset'),
  ('The winning mind treats ''no'' as a detour, not a destination.', null, 'mindset'),
  ('Your inner narrative is your greatest competitive advantage.', null, 'mindset'),
  ('A setback is just a slingshot—pull back to launch forward.', null, 'resilience'),
  ('The comeback is always greater than the setback.', null, 'resilience'),
  ('Bend in the storm; do not break.', null, 'resilience'),
  ('Resilience is not bouncing back—it is bouncing forward.', null, 'resilience'),
  ('Hard seasons do not define you—your response to them does.', null, 'resilience'),
  ('If you fell, you were moving—get up and keep moving.', null, 'resilience'),
  ('The strongest trees grow in the most wind.', null, 'resilience'),
  ('Every tough day is building a tougher version of you.', null, 'resilience'),
  ('Failure is not the end—it is the training you needed.', null, 'resilience'),
  ('When the path disappears, champions make a new one.', null, 'resilience'),
  ('Being knocked down is temporary; staying down is a choice.', null, 'resilience'),
  ('The test of character is not what you do when it is easy.', null, 'resilience'),
  ('You have survived every hard day so far—this one is no different.', null, 'resilience'),
  ('Pain is the price of growth—pay it without complaint.', null, 'resilience'),
  ('The deeper the valley, the higher the peak ahead.', null, 'resilience'),
  ('Scars are proof you healed—keep going.', null, 'resilience'),
  ('When everything feels wrong, one right action starts the turn.', null, 'resilience'),
  ('You are not broken; you are mid-repair.', null, 'resilience'),
  ('Dust off and reload—every reset is a fresh attempt.', null, 'resilience'),
  ('Your grit today is your confidence tomorrow.', null, 'resilience'),
  ('Discipline is freedom—the freedom to become who you promised yourself.', null, 'discipline'),
  ('Show up even when it costs you—especially when it costs you.', null, 'discipline'),
  ('The unglamorous hours are where legends are forged.', null, 'discipline'),
  ('Discipline is doing the right thing when no one is watching.', null, 'discipline'),
  ('A habit practiced daily becomes identity.', null, 'discipline'),
  ('You do not need inspiration—you need a decision and a start time.', null, 'discipline'),
  ('Success does not follow the excited; it follows the consistent.', null, 'discipline'),
  ('Build systems, not just dreams—systems run when motivation sleeps.', null, 'discipline'),
  ('The easy choice now is the hard life later; the hard choice now is the easy life later.', null, 'discipline'),
  ('Routine is the skeleton of greatness—build it deliberately.', null, 'discipline'),
  ('Discipline is the bridge between goals and accomplishment.', null, 'discipline'),
  ('Do it tired, do it scared, do it imperfectly—just do it.', null, 'discipline'),
  ('Every morning you execute your plan, the universe takes you more seriously.', null, 'discipline'),
  ('A little done daily defeats a lot done occasionally.', null, 'discipline'),
  ('The disciplined person bends time to their will.', null, 'discipline'),
  ('Your choices compound—make sure they are adding up to something.', null, 'discipline'),
  ('Willpower is a muscle; the gym is your daily schedule.', null, 'discipline'),
  ('Sacrifice a comfortable now for an extraordinary later.', null, 'discipline'),
  ('Precision and repetition—the two words that built every legend.', null, 'discipline'),
  ('The person who masters boredom masters their field.', null, 'discipline'),
  ('Structure is not a cage; it is a launchpad.', null, 'discipline'),
  ('If you cannot control your schedule, you cannot control your outcomes.', null, 'discipline'),
  ('Clarity is the rarest superpower—protect it fiercely.', null, 'focus'),
  ('Do fewer things with full attention and more gets done.', null, 'focus'),
  ('Where focus goes, energy flows and results show.', null, 'focus'),
  ('Eliminate the noise until only signal remains.', null, 'focus'),
  ('A scattered mind produces scattered results.', null, 'focus'),
  ('The most powerful thing you can do is finish what you started.', null, 'focus'),
  ('Deep work is the new competitive advantage—go deep.', null, 'focus'),
  ('Block the distraction before it blocks your destiny.', null, 'focus'),
  ('Multitasking is doing several things poorly at once.', null, 'focus'),
  ('Protect your peak hours like they are the most valuable currency—because they are.', null, 'focus'),
  ('Laser focus on today is the secret weapon for a brilliant tomorrow.', null, 'focus'),
  ('The path narrows when you stop chasing everything and start pursuing one thing.', null, 'focus'),
  ('Commit completely to the task in front of you—it will return the favor.', null, 'focus'),
  ('Singular attention multiplies results.', null, 'focus'),
  ('Turn off the noise, open the work, begin.', null, 'focus'),
  ('Brilliant minds waste no attention on what does not matter.', null, 'focus'),
  ('A crystal-clear goal makes every decision obvious.', null, 'focus'),
  ('What you choose to ignore determines what you get to achieve.', null, 'focus'),
  ('You cannot pour from a distracted mind—focus first.', null, 'focus'),
  ('The champion''s edge is not extra talent—it is undivided attention.', null, 'focus'),
  ('Boundaries protect your focus; focus builds your future.', null, 'focus'),
  ('One hour of deep focus outweighs three hours of half-presence.', null, 'focus'),
  ('Small steps taken daily move mountains over time.', null, 'consistency'),
  ('The secret to overnight success is years of consistent invisible work.', null, 'consistency'),
  ('You do not have to be extreme—just be consistent.', null, 'consistency'),
  ('Every drop fills the ocean; every effort fills your potential.', null, 'consistency'),
  ('Progress is quiet, slow, and unstoppable when consistent.', null, 'consistency'),
  ('Consistency is the ultimate form of confidence.', null, 'consistency'),
  ('The compound effect rewards those who refuse to quit on their routine.', null, 'consistency'),
  ('Champions are not born in a single great moment—they are built in ordinary ones.', null, 'consistency'),
  ('Reliability over time is the definition of trustworthy—even to yourself.', null, 'consistency'),
  ('The best version of you is 1% better, every single day.', null, 'consistency'),
  ('Streaks are not the goal—habits are. Habits outlast streaks.', null, 'consistency'),
  ('Win the morning, win the day, win enough days to win the year.', null, 'consistency'),
  ('You cannot rush compound growth—you can only protect your inputs.', null, 'consistency'),
  ('Show up in October as you showed up in January—and watch what happens.', null, 'consistency'),
  ('Long games reward patient players who keep showing up.', null, 'consistency'),
  ('The one who sticks around wins.', null, 'consistency'),
  ('Consistent effort is quietly building something extraordinary.', null, 'consistency'),
  ('Water does not rush—it flows, it persists, it shapes mountains.', null, 'consistency'),
  ('Repetition is not boring—it is the language of mastery.', null, 'consistency'),
  ('Talent sets the ceiling; consistency raises the floor.', null, 'consistency'),
  ('Your daily output is your annual report—make it count.', null, 'consistency'),
  ('Be boring in your habits and extraordinary in your results.', null, 'consistency'),
  ('Win today first—tomorrow will take care of itself.', null, 'daily_win'),
  ('A single completed task beats a hundred intentions.', null, 'daily_win'),
  ('Today''s small win is tomorrow''s strong foundation.', null, 'daily_win'),
  ('Mark one thing done before noon and watch your day shift.', null, 'daily_win'),
  ('Check one box today. One is never zero.', null, 'daily_win'),
  ('The day is won in the first hour—set the tone.', null, 'daily_win'),
  ('Tiny victories add up to trophy moments.', null, 'daily_win'),
  ('Do one hard thing today and the rest of the day feels lighter.', null, 'daily_win'),
  ('Every task completed is a vote for your capable self.', null, 'daily_win'),
  ('A win, no matter how small, is still a win—log it.', null, 'daily_win'),
  ('Start before you are ready; the readiness comes mid-motion.', null, 'daily_win'),
  ('Done imperfectly today beats perfect in your head forever.', null, 'daily_win'),
  ('Make today non-negotiable: one honest attempt minimum.', null, 'daily_win'),
  ('Cross one thing off the list. Crossing it off changes everything.', null, 'daily_win'),
  ('The best time was yesterday; the second best time is right now.', null, 'daily_win'),
  ('You do not need a perfect day—just a purposeful one.', null, 'daily_win'),
  ('End today with fewer regrets than yesterday started with.', null, 'daily_win'),
  ('One step forward is still forward—celebrate it.', null, 'daily_win'),
  ('Collect small victories the way others collect excuses.', null, 'daily_win'),
  ('Today''s execution is tomorrow''s momentum.', null, 'daily_win'),
  ('Begin. Just begin. The rest follows from there.', null, 'daily_win'),
  ('If you did at least one thing that mattered today, you won.', null, 'daily_win'),
  ('You are not the same person who started—that is the whole point.', null, 'growth'),
  ('Growth is uncomfortable because it requires you to outgrow yourself.', null, 'growth'),
  ('Every expert was once a beginner who kept going.', null, 'growth'),
  ('Struggle is not the enemy of growth—it is the mechanism.', null, 'growth'),
  ('The version of you one year from now depends on what you do today.', null, 'growth'),
  ('You grow at the edge of your comfort zone, not in the center of it.', null, 'growth'),
  ('Every chapter of your story has something to teach—read it carefully.', null, 'growth'),
  ('Learning from failure is not consolation—it is strategy.', null, 'growth'),
  ('Growth requires honesty: see where you are, decide where to go.', null, 'growth'),
  ('The student who improves by 1% daily is unbeatable over a year.', null, 'growth'),
  ('You are either growing or shrinking—there is no standing still.', null, 'growth'),
  ('Your ceiling is your current thinking—expand the thinking, raise the ceiling.', null, 'growth'),
  ('The biggest room in the world is the room for self-improvement.', null, 'growth'),
  ('Invest in yourself today; compound interest has no rivals.', null, 'growth'),
  ('Excellence is not a destination—it is a daily direction.', null, 'growth'),
  ('Every skill you add today closes a gap between you and your goal.', null, 'growth'),
  ('The uncomfortable question moves you forward faster than the comfortable answer.', null, 'growth'),
  ('Stretch beyond what feels safe—that is where your next level lives.', null, 'growth'),
  ('The gap between amateur and expert is filled with repetitions most people quit before.', null, 'growth'),
  ('Feedback is a gift—thank it, process it, grow from it.', null, 'growth'),
  ('Every good habit installed today earns interest for a lifetime.', null, 'growth'),
  ('The person who never stops learning never stops winning.', null, 'growth'),
  ('Replace ego with curiosity and watch every obstacle become a lesson.', null, 'growth'),
  ('Build yourself in private; show up transformed in public.', null, 'growth'),
  ('The version of you capable of your goals is built in daily sessions, not sudden transformations.', null, 'growth');
